// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ExampleEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject exampleEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ExampleEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		StringAttrNoDef("StringAttrNoDef"),
		StringAttr("StringAttr"),
		IntegerAttr("IntegerAttr"),
		IntegerAttrNoDef("IntegerAttrNoDef"),
		LongAttr("LongAttr"),
		LongAttrNoDef("LongAttrNoDef"),
		BooleanAttr("BooleanAttr"),
		DateTimeAttr("DateTimeAttr"),
		DateTimeAttrNoDef("DateTimeAttrNoDef"),
		EnumAttr("EnumAttr"),
		EnumAttrNoDef("EnumAttrNoDef"),
		CalculatedAttr("CalculatedAttr"),
		DecimalAttr("DecimalAttr");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExampleEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.ExampleEntity"));
	}

	protected ExampleEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject exampleEntityMendixObject)
	{
		if (exampleEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.ExampleEntity", exampleEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.ExampleEntity");

		this.exampleEntityMendixObject = exampleEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ExampleEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.ExampleEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ExampleEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.ExampleEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ExampleEntity(context, mendixObject);
	}

	public static myfirstmodule.proxies.ExampleEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ExampleEntity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ExampleEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.ExampleEntity> result = new java.util.ArrayList<myfirstmodule.proxies.ExampleEntity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.ExampleEntity" + xpathConstraint))
			result.add(myfirstmodule.proxies.ExampleEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of StringAttrNoDef
	 */
	public final java.lang.String getStringAttrNoDef()
	{
		return getStringAttrNoDef(getContext());
	}

	/**
	 * @param context
	 * @return value of StringAttrNoDef
	 */
	public final java.lang.String getStringAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringAttrNoDef.toString());
	}

	/**
	 * Set value of StringAttrNoDef
	 * @param stringattrnodef
	 */
	public final void setStringAttrNoDef(java.lang.String stringattrnodef)
	{
		setStringAttrNoDef(getContext(), stringattrnodef);
	}

	/**
	 * Set value of StringAttrNoDef
	 * @param context
	 * @param stringattrnodef
	 */
	public final void setStringAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringattrnodef)
	{
		getMendixObject().setValue(context, MemberNames.StringAttrNoDef.toString(), stringattrnodef);
	}

	/**
	 * @return value of StringAttr
	 */
	public final java.lang.String getStringAttr()
	{
		return getStringAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of StringAttr
	 */
	public final java.lang.String getStringAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringAttr.toString());
	}

	/**
	 * Set value of StringAttr
	 * @param stringattr
	 */
	public final void setStringAttr(java.lang.String stringattr)
	{
		setStringAttr(getContext(), stringattr);
	}

	/**
	 * Set value of StringAttr
	 * @param context
	 * @param stringattr
	 */
	public final void setStringAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringattr)
	{
		getMendixObject().setValue(context, MemberNames.StringAttr.toString(), stringattr);
	}

	/**
	 * @return value of IntegerAttr
	 */
	public final java.lang.Integer getIntegerAttr()
	{
		return getIntegerAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of IntegerAttr
	 */
	public final java.lang.Integer getIntegerAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntegerAttr.toString());
	}

	/**
	 * Set value of IntegerAttr
	 * @param integerattr
	 */
	public final void setIntegerAttr(java.lang.Integer integerattr)
	{
		setIntegerAttr(getContext(), integerattr);
	}

	/**
	 * Set value of IntegerAttr
	 * @param context
	 * @param integerattr
	 */
	public final void setIntegerAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integerattr)
	{
		getMendixObject().setValue(context, MemberNames.IntegerAttr.toString(), integerattr);
	}

	/**
	 * @return value of IntegerAttrNoDef
	 */
	public final java.lang.Integer getIntegerAttrNoDef()
	{
		return getIntegerAttrNoDef(getContext());
	}

	/**
	 * @param context
	 * @return value of IntegerAttrNoDef
	 */
	public final java.lang.Integer getIntegerAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntegerAttrNoDef.toString());
	}

	/**
	 * Set value of IntegerAttrNoDef
	 * @param integerattrnodef
	 */
	public final void setIntegerAttrNoDef(java.lang.Integer integerattrnodef)
	{
		setIntegerAttrNoDef(getContext(), integerattrnodef);
	}

	/**
	 * Set value of IntegerAttrNoDef
	 * @param context
	 * @param integerattrnodef
	 */
	public final void setIntegerAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integerattrnodef)
	{
		getMendixObject().setValue(context, MemberNames.IntegerAttrNoDef.toString(), integerattrnodef);
	}

	/**
	 * @return value of LongAttr
	 */
	public final java.lang.Long getLongAttr()
	{
		return getLongAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of LongAttr
	 */
	public final java.lang.Long getLongAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongAttr.toString());
	}

	/**
	 * Set value of LongAttr
	 * @param longattr
	 */
	public final void setLongAttr(java.lang.Long longattr)
	{
		setLongAttr(getContext(), longattr);
	}

	/**
	 * Set value of LongAttr
	 * @param context
	 * @param longattr
	 */
	public final void setLongAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longattr)
	{
		getMendixObject().setValue(context, MemberNames.LongAttr.toString(), longattr);
	}

	/**
	 * @return value of LongAttrNoDef
	 */
	public final java.lang.Long getLongAttrNoDef()
	{
		return getLongAttrNoDef(getContext());
	}

	/**
	 * @param context
	 * @return value of LongAttrNoDef
	 */
	public final java.lang.Long getLongAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongAttrNoDef.toString());
	}

	/**
	 * Set value of LongAttrNoDef
	 * @param longattrnodef
	 */
	public final void setLongAttrNoDef(java.lang.Long longattrnodef)
	{
		setLongAttrNoDef(getContext(), longattrnodef);
	}

	/**
	 * Set value of LongAttrNoDef
	 * @param context
	 * @param longattrnodef
	 */
	public final void setLongAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longattrnodef)
	{
		getMendixObject().setValue(context, MemberNames.LongAttrNoDef.toString(), longattrnodef);
	}

	/**
	 * @return value of BooleanAttr
	 */
	public final java.lang.Boolean getBooleanAttr()
	{
		return getBooleanAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanAttr
	 */
	public final java.lang.Boolean getBooleanAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanAttr.toString());
	}

	/**
	 * Set value of BooleanAttr
	 * @param booleanattr
	 */
	public final void setBooleanAttr(java.lang.Boolean booleanattr)
	{
		setBooleanAttr(getContext(), booleanattr);
	}

	/**
	 * Set value of BooleanAttr
	 * @param context
	 * @param booleanattr
	 */
	public final void setBooleanAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanattr)
	{
		getMendixObject().setValue(context, MemberNames.BooleanAttr.toString(), booleanattr);
	}

	/**
	 * @return value of DateTimeAttr
	 */
	public final java.util.Date getDateTimeAttr()
	{
		return getDateTimeAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeAttr
	 */
	public final java.util.Date getDateTimeAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeAttr.toString());
	}

	/**
	 * Set value of DateTimeAttr
	 * @param datetimeattr
	 */
	public final void setDateTimeAttr(java.util.Date datetimeattr)
	{
		setDateTimeAttr(getContext(), datetimeattr);
	}

	/**
	 * Set value of DateTimeAttr
	 * @param context
	 * @param datetimeattr
	 */
	public final void setDateTimeAttr(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimeattr)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeAttr.toString(), datetimeattr);
	}

	/**
	 * @return value of DateTimeAttrNoDef
	 */
	public final java.util.Date getDateTimeAttrNoDef()
	{
		return getDateTimeAttrNoDef(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeAttrNoDef
	 */
	public final java.util.Date getDateTimeAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeAttrNoDef.toString());
	}

	/**
	 * Set value of DateTimeAttrNoDef
	 * @param datetimeattrnodef
	 */
	public final void setDateTimeAttrNoDef(java.util.Date datetimeattrnodef)
	{
		setDateTimeAttrNoDef(getContext(), datetimeattrnodef);
	}

	/**
	 * Set value of DateTimeAttrNoDef
	 * @param context
	 * @param datetimeattrnodef
	 */
	public final void setDateTimeAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimeattrnodef)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeAttrNoDef.toString(), datetimeattrnodef);
	}

	/**
	 * Set value of EnumAttr
	 * @param enumattr
	 */
	public final myfirstmodule.proxies.TestEnum getEnumAttr()
	{
		return getEnumAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumAttr
	 */
	public final myfirstmodule.proxies.TestEnum getEnumAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumAttr.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.TestEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumAttr
	 * @param enumattr
	 */
	public final void setEnumAttr(myfirstmodule.proxies.TestEnum enumattr)
	{
		setEnumAttr(getContext(), enumattr);
	}

	/**
	 * Set value of EnumAttr
	 * @param context
	 * @param enumattr
	 */
	public final void setEnumAttr(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TestEnum enumattr)
	{
		if (enumattr != null)
			getMendixObject().setValue(context, MemberNames.EnumAttr.toString(), enumattr.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnumAttr.toString(), null);
	}

	/**
	 * Set value of EnumAttrNoDef
	 * @param enumattrnodef
	 */
	public final myfirstmodule.proxies.TestEnum getEnumAttrNoDef()
	{
		return getEnumAttrNoDef(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumAttrNoDef
	 */
	public final myfirstmodule.proxies.TestEnum getEnumAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumAttrNoDef.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.TestEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumAttrNoDef
	 * @param enumattrnodef
	 */
	public final void setEnumAttrNoDef(myfirstmodule.proxies.TestEnum enumattrnodef)
	{
		setEnumAttrNoDef(getContext(), enumattrnodef);
	}

	/**
	 * Set value of EnumAttrNoDef
	 * @param context
	 * @param enumattrnodef
	 */
	public final void setEnumAttrNoDef(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TestEnum enumattrnodef)
	{
		if (enumattrnodef != null)
			getMendixObject().setValue(context, MemberNames.EnumAttrNoDef.toString(), enumattrnodef.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnumAttrNoDef.toString(), null);
	}

	/**
	 * @return value of CalculatedAttr
	 */
	public final java.lang.String getCalculatedAttr()
	{
		return getCalculatedAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of CalculatedAttr
	 */
	public final java.lang.String getCalculatedAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CalculatedAttr.toString());
	}

	/**
	 * Set value of CalculatedAttr
	 * @param calculatedattr
	 */
	public final void setCalculatedAttr(java.lang.String calculatedattr)
	{
		setCalculatedAttr(getContext(), calculatedattr);
	}

	/**
	 * Set value of CalculatedAttr
	 * @param context
	 * @param calculatedattr
	 */
	public final void setCalculatedAttr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calculatedattr)
	{
		getMendixObject().setValue(context, MemberNames.CalculatedAttr.toString(), calculatedattr);
	}

	/**
	 * @return value of DecimalAttr
	 */
	public final java.math.BigDecimal getDecimalAttr()
	{
		return getDecimalAttr(getContext());
	}

	/**
	 * @param context
	 * @return value of DecimalAttr
	 */
	public final java.math.BigDecimal getDecimalAttr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecimalAttr.toString());
	}

	/**
	 * Set value of DecimalAttr
	 * @param decimalattr
	 */
	public final void setDecimalAttr(java.math.BigDecimal decimalattr)
	{
		setDecimalAttr(getContext(), decimalattr);
	}

	/**
	 * Set value of DecimalAttr
	 * @param context
	 * @param decimalattr
	 */
	public final void setDecimalAttr(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimalattr)
	{
		getMendixObject().setValue(context, MemberNames.DecimalAttr.toString(), decimalattr);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return exampleEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ExampleEntity that = (myfirstmodule.proxies.ExampleEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.ExampleEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
