// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csv.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Writes the object attribute names to the CSV file. The input entity parameter should match the input parameter of the WriteNextLine action.
 */
public class WriteHeaderToCSV extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String entity;

	public WriteHeaderToCSV(IContext context, java.lang.String entity)
	{
		super(context);
		this.entity = entity;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE		
		ILogNode logger = CSV.getLogger();
		CSVWriter writer = CSV.getCSVWriter(getContext());
		@SuppressWarnings("resource") // reader is closed by the ImportCSV action

		IMetaObject metaObject = Core.getMetaObject(entity);

		String[] attributes = CSV.getAttributes(metaObject);

		writer.writeNext(attributes);
		logger.trace("Written header to CSV.");
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "WriteHeaderToCSV";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
